plugins {
    id 'java'
    id 'application'
}

group = 'es.laucher.cobblemon'
version = '0.1.0'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'es.laucher.cobblemon.LaucherCobblemon'
}

jar {
    manifest {
        attributes 'Main-Class': application.mainClass.get()
    }
}
